version: "3"

services:

  app:
    build: .
    restart: always
    environment:
      - NODEJS_PORT=3000
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - mongo
  
  mongo:
    restart: always
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - 127.0.0.1:27018:27017
